[package]
name = "sagoin"
version = "0.1.0"
authors = ["figsoda <figsoda@pm.me>"]
edition = "2021"
description = ""
readme = "README.md"
homepage = "https://github.com/figsoda/sagoin"
repository = "https://github.com/figsoda/sagoin"
license = "AGPL-3.0-or-later"
keywords = []
categories = []

[dependencies]

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
