[package]
name = "sagoin"
version = "0.1.0"
authors = ["figsoda <figsoda@pm.me>"]
edition = "2021"
description = ""
readme = "README.md"
homepage = "https://github.com/figsoda/sagoin"
repository = "https://github.com/figsoda/sagoin"
license = "AGPL-3.0-or-later"
keywords = []
categories = []

[dependencies]
anyhow = "1.0.65"
ignore = "0.4.18"
is_executable = "1.0.1"
java-properties = "1.4.1"
zip = "0.6.2"

[dependencies.clap]
version = "3.2.22"
features = ["cargo", "derive", "unicode"]

[dependencies.reqwest]
version = "0.11.11"
default-features = false
features = ["multipart", "rustls-tls"]

[dependencies.tokio]
version = "1.21.1"
features = ["macros", "rt-multi-thread"]

[build-dependencies]
clap = { version = "3.2.22", features = ["derive"] }
clap_complete = "3.2.5"

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
