[package]
name = "sagoin"
version = "0.1.0"
authors = ["figsoda <figsoda@pm.me>"]
edition = "2021"
description = ""
readme = "README.md"
homepage = "https://github.com/figsoda/sagoin"
repository = "https://github.com/figsoda/sagoin"
license = "AGPL-3.0-or-later"
keywords = []
categories = []

[dependencies]
anyhow = "1.0.65"
icalendar = { version = "0.13.1", features = ["parser"] }
ignore = "0.4.18"
is_executable = "1.0.1"
java-properties = "1.4.1"
rpassword = "7.0.0"
ureq = "2.5.0"
webbrowser = "0.8.0"
zip = { version = "0.6.2", default-features = false }

[dependencies.clap]
version = "4.0.2"
features = ["cargo", "derive", "unicode"]

[dependencies.multipart]
version = "0.18.0"
default-features = false
features = ["client"]

[build-dependencies]
clap = { version = "4.0.2", features = ["derive"] }
clap_complete = "4.0.1"

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
